### ISSUE TITLE
Why form ressource is load by the extension ?

### ISSUE THREAD

**Issue by lpxavi** [excelwebzone/EWZRecaptchaBundle#128]
Hi,

I have noticed the form resources are loaded by the bundle extension.

In the Symfony documentation, form resources are loaded in framework config
(https://symfony.com/doc/current/form/form_customization.html#making-application-wide-customizations).
### Twig engine :
```
# app/config/config.yml
twig:
    form_themes:
       - 'form/ewz_recaptcha_widget.html.twig'

```
### PHP engine :
```
# app/config/config.yml
framework:
    templating:
        form:
            resources:
                - 'EWZRecaptchaBundle:Form'

```
Why do you choose to use the bundle extension to load form resource ?

Tks you !
