### ISSUE TITLE
Fix compatibility with Symfony 4

### ISSUE THREAD

**Issue by jmsche** [excelwebzone/EWZRecaptchaBundle#188]
When trying to install the bundle for Symfony 4, the following error is thrown:

> You have requested a non-existent parameter "templating.engines".

**Comment by tibo6** [comment]
And I have

> You have requested a non-existent parameter "twig.form.resources".

**Comment by someniatko** [comment]
I fixed this for myself by creating `config/ewz_recaptcha.yaml` wich the following content:

```
parameters:
    templating.engines: [ 'twig' ]
    twig.form.resources: []

ewz_recaptcha:
    public_key: ''
    private_key: ''```

**Comment by jmsche** [comment]
Templating component seems to be deprecated.
Then Twig should be called directly instead of specifying extra config.

**Comment by bobvandevijver** [comment]
In my project I needed to do the following in order to make it work (which is probably caused by the custom form_theme used):

```yaml
twig:
  paths:
    '%kernel.project_dir%/templates': App
    '%kernel.project_dir%/vendor/excelwebzone/recaptcha-bundle/src/Resources/views': ewz_recaptcha
  form_themes:
    - "@ewz_recaptcha/Form/ewz_recaptcha_widget.html.twig"
    - "form/form_layout.html.twig"
```

Next to that, make sure to set the parameter used to determine the engine so that it will not load anything by itself (as it breaks):
```yaml
parameters:
  templating.engines: [ 'none' ]
```
