### ISSUE TITLE
 InvalidConfigurationException  The child node "public_key" at path "ewz_recaptcha" must be configured.

### ISSUE THREAD

**Issue by mn000** [excelwebzone/EWZRecaptchaBundle#213]
I got this error, i added site key and secret key in .env file. I use symfony4.
```
 InvalidConfigurationException
The child node "public_key" at path "ewz_recaptcha" must be configured.
```
Please help

**Comment by elvismdev** [comment]
@mn000 You need to add the configuration file for the bundle yourself first. Add it inside `config/packages` directory (e.g. `config/packages/ewz_recaptcha.yaml`). And add the needed config inside there:

```
ewz_recaptcha:
  public_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
  locale_key:  '%kernel.default_locale%'
  locale_from_request: true
  # ajax: true
  # enabled: false
  # verify_host: true
```
Then re-run the bundle installation from composer.
