### ISSUE TITLE
Validation doesn't work in test environment when passing the validation constraints as an option to the FormType

### ISSUE THREAD

**Issue by steevechristen** [excelwebzone/EWZRecaptchaBundle#252]
When passing the validation constraints as an option to the FormType (as described in the readme)
```php
        'constraints' => array(
            new RecaptchaTrue()
        )
```
the validation is done even if the reCAPTCHA is disabled
```yml
ewz_recaptcha:
    // ...
    enabled: false
```

This isn't a problem as long as a valid `ewz_recaptcha.public_key` is defined.

In test environment, we might have the reCAPTCHA disabled and empty keys:
```yml
ewz_recaptcha:
    public_key: ''
    private_key: ''
    enabled: false
```

The validation would then trigger a RuntimeException "No secret provided", since `ReCaptcha/ReCaptcha` requires a non empty value as first `$secret` parameter.

A way to solve this problem would be to set the `validation_groups` option of the FormType to `false` when the reCAPTCHA is disabled.
